/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.DatabaseService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FleetManager;
import model.LuxuryCar;
import model.Vehicle;
/**
 *
 * @author xxx
 */
public class Dashboard extends javax.swing.JFrame {
    private model.FleetManager manager;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        manager = new FleetManager();
        DatabaseService.loadFleetData(manager);
        refreshTable();
    }
     private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) fleetTable.getModel();
    model.setRowCount(0);
    model.setColumnIdentifiers(new String[]{"Type", "VIN", "Model", "Year", "Odometer (KM)"});

    for (Vehicle v : manager.getFleetList()) {
        // فحص نوع الكائن برمجياً وتحديد النص المناسب للجدول
        String type = "Unknown";
        if (v instanceof model.LuxuryCar) {
            type = "Luxury Car";
        } else if (v instanceof model.Truck) {
            type = "Truck";
        }
        
        model.addRow(new Object[]{type, v.getVin(), v.getModel(), v.getYear(), v.getCurrentOdometer()});
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fleetTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addButton.setText("Add vehicle");
        addButton.addActionListener(this::addButtonActionPerformed);
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        fleetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VIN", "Model Name", "year", "Odometer"
            }
        ));
        jScrollPane1.setViewportView(fleetTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
        // 1. نسأل المستخدم أولاً عن نوع المركبة باستخدام نافذة خيارات
        String[] options = {"Luxury Car", "Truck"};
        String selectedType = (String) javax.swing.JOptionPane.showInputDialog(
                this, 
                "Select Vehicle Type:", 
                "Vehicle Type", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, 
                options, 
                options[0]
        );
        
        // إذا قفل المستخدم النافذة أو ألغى الإدخال
        if (selectedType == null) return;

        // 2. نطلب باقي البيانات المعتادة (رقم الهيكل، الموديل، السنة، العداد)
        String vin = javax.swing.JOptionPane.showInputDialog(this, "Enter Vehicle VIN (رقم الهيكل):");
        if (vin == null || vin.trim().isEmpty()) return;

        String modelName = javax.swing.JOptionPane.showInputDialog(this, "Enter Vehicle Model (الموديل):");
        if (modelName == null || modelName.trim().isEmpty()) return;
        
        String yearStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Manufacture Year (سنة الصنع):");
        int year = Integer.parseInt(yearStr);

        String odoStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Current Odometer (العداد):");
        double odometer = Double.parseDouble(odoStr);

        // 3. هنا السحر البرمجي! بناءً على اختيار المستخدم نقوم بإنشاء الكائن الصحيح
        if (selectedType.equals("Luxury Car")) {
            model.LuxuryCar newCar = new model.LuxuryCar(vin, modelName, year, odometer);
            manager.addVehicle(newCar);
        } else if (selectedType.equals("Truck")) {
            model.Truck newTruck = new model.Truck(vin, modelName, year, odometer);
            manager.addVehicle(newTruck); // إضافة الشاحنة للأسطول
        }

        // 4. حفظ الأسطول بالكامل وتحديث الجدول فوراً
        database.DatabaseService.saveFleetData(manager);
        refreshTable();

        javax.swing.JOptionPane.showMessageDialog(this, selectedType + " Added and Saved Successfully!");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid input! Year and Odometer must be numbers.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable fleetTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
