/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.DatabaseService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FleetManager;
import model.LuxuryCar;
import model.Vehicle;
/**
 *
 * @author xxx
 */
public class Dashboard extends javax.swing.JFrame {
    private model.FleetManager manager;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        manager = new FleetManager();
        DatabaseService.loadFleetData(manager);
        refreshTable();
    }
     private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) fleetTable.getModel();
    model.setRowCount(0);
    model.setColumnIdentifiers(new String[]{"Type", "VIN", "Model", "Year", "Odometer (KM)"});

    for (Vehicle v : manager.getFleetList()) {
        // فحص نوع الكائن برمجياً وتحديد النص المناسب للجدول
        String type = "Unknown";
        if (v instanceof model.LuxuryCar) {
            type = "Luxury Car";
        } else if (v instanceof model.Truck) {
            type = "Truck";
        }
        
        model.addRow(new Object[]{type, v.getVin(), v.getModel(), v.getYear(), v.getCurrentOdometer()});
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fleetTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addMaintenanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addButton.setText("Add vehicle");
        addButton.addActionListener(this::addButtonActionPerformed);
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        fleetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VIN", "Model Name", "year", "Odometer"
            }
        ));
        jScrollPane1.setViewportView(fleetTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jButton2.setText("Calculate Fleet Cost");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        updateButton.setText("Edit");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        addMaintenanceButton.setText("Add Maintenance");
        addMaintenanceButton.addActionListener(this::addMaintenanceButtonActionPerformed);
        getContentPane().add(addMaintenanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
        // 1. نسأل المستخدم أولاً عن نوع المركبة باستخدام نافذة خيارات
        String[] options = {"Luxury Car", "Truck"};
        String selectedType = (String) javax.swing.JOptionPane.showInputDialog(
                this, 
                "Select Vehicle Type:", 
                "Vehicle Type", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, 
                options, 
                options[0]
        );
        
        // إذا قفل المستخدم النافذة أو ألغى الإدخال
        if (selectedType == null) return;

        // 2. نطلب باقي البيانات المعتادة (رقم الهيكل، الموديل، السنة، العداد)
        String vin = javax.swing.JOptionPane.showInputDialog(this, "Enter Vehicle VIN (رقم الهيكل):");
        if (vin == null || vin.trim().isEmpty()) return;

        String modelName = javax.swing.JOptionPane.showInputDialog(this, "Enter Vehicle Model (الموديل):");
        if (modelName == null || modelName.trim().isEmpty()) return;
        
        String yearStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Manufacture Year (سنة الصنع):");
        int year = Integer.parseInt(yearStr);

        String odoStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Current Odometer (العداد):");
        double odometer = Double.parseDouble(odoStr);

        // 3. هنا السحر البرمجي! بناءً على اختيار المستخدم نقوم بإنشاء الكائن الصحيح
        if (selectedType.equals("Luxury Car")) {
            model.LuxuryCar newCar = new model.LuxuryCar(vin, modelName, year, odometer);
            manager.addVehicle(newCar);
        } else if (selectedType.equals("Truck")) {
            model.Truck newTruck = new model.Truck(vin, modelName, year, odometer);
            manager.addVehicle(newTruck); // إضافة الشاحنة للأسطول
        }

        // 4. حفظ الأسطول بالكامل وتحديث الجدول فوراً
        database.DatabaseService.saveFleetData(manager);
        refreshTable();

        javax.swing.JOptionPane.showMessageDialog(this, selectedType + " Added and Saved Successfully!");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid input! Year and Odometer must be numbers.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    // 1. التأكد من أن المستخدم حدد سيارة من الجدول
    int selectedRow = fleetTable.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please select a specific vehicle from the table to view its individual maintenance report.", 
            "Selection Required", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. جلب رقم الهيكل الـ VIN والموديل من السطر المحدد (العمود الثاني والثالث)
    String selectedVin = fleetTable.getValueAt(selectedRow, 1).toString();
    String selectedModel = fleetTable.getValueAt(selectedRow, 2).toString();
    
    // 3. البحث عن المركبة داخل قائمة الأسطول
    for (model.Vehicle v : manager.getFleetList()) {
        if (v.getVin().equals(selectedVin)) {
            
            // جلب تاريخ سجلات الصيانة الخاص بهذه المركبة بالتحديد
            java.util.ArrayList<model.MaintenanceRecord> history = v.getMaintenanceHistory();
            
            // إذا لم يتم إضافة أي صيانة لهذه السيارة حتى الآن
            if (history == null || history.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "No maintenance records found for Vehicle (Model: " + selectedModel + ", VIN: " + selectedVin + ").\nTotal Cost: $0.00", 
                    "Individual Report", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // 4. بناء نص التقرير المفصل والفاتورة المنسقة
            StringBuilder report = new StringBuilder();
            report.append("==================================================\n");
            report.append("          FLEET MAINTENANCE SYSTEM - INVOICE       \n");
            report.append("==================================================\n");
            report.append("Date of Issue: 2026-06-22\n");
            report.append("Vehicle Model: ").append(selectedModel).append("\n");
            report.append("VIN Number   : ").append(selectedVin).append("\n");
            report.append("--------------------------------------------------\n");
            report.append(String.format("%-18s | %-12s | %-10s\n", "Service Type", "Cost", "Date"));
            report.append("--------------------------------------------------\n");
            
            // التكرار لعرض كل خدمة وسعرها وتاريخها
            for (model.MaintenanceRecord record : history) {
                report.append(String.format("%-18s | $%-11.2f | %-10s\n", 
                        record.getServiceType(), 
                        record.getCost(), 
                        record.getDate()));
            }
            
            report.append("--------------------------------------------------\n");
            // حساب المجموع الخاص بهذه السيارة فقط ديناميكياً
            report.append(String.format("TOTAL AMOUNT DUE: $%.2f\n", v.calculateMaintenanceCost()));
            report.append("==================================================\n");
            report.append("            Thank you for your business!          \n");
            report.append("==================================================\n");
            
            // 5. إنشاء منطقة النص وضبط الإعدادات والخط
            final javax.swing.JTextArea textArea = new javax.swing.JTextArea(report.toString());
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
            textArea.setEditable(false);
            
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(480, 360));
            
            // 6. الحل هنا: تحديد الأزرار المخصصة التي ستظهر أسفل النافذة جنب بعضها
            String[] options = {"Print Invoice", "Close"};
            
            int choice = javax.swing.JOptionPane.showOptionDialog(
                this, 
                scrollPane, 
                "Vehicle Maintenance Report", 
                javax.swing.JOptionPane.DEFAULT_OPTION, 
                javax.swing.JOptionPane.PLAIN_MESSAGE, 
                null, 
                options, 
                options[0] // الزر الافتراضي المحدد هو طباعة
            );
            
            // 7. إذا ضغط المستخدم على زر Print Invoice، نقوم باستدعاء نافذة الطباعة الحقيقية للجهاز
            if (choice == 0) {
                try {
                    boolean complete = textArea.print();
                    if (complete) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Printing Complete!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (java.awt.print.PrinterException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Printing Failed: " + e.getMessage(), "Print Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
                
            return; // الخروج من الدالة بعد العثور على السيارة وعرض تقريرها
        }
    }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        // 1. معرفة السطر الذي حدده المستخدم بالفأرة في الجدول
    int selectedRow = fleetTable.getSelectedRow();
    
    // إذا لم يحدد المستخدم أي سطر، نظهر له رسالة تحذير
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a vehicle from the table to delete.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. جلب رقم الهيكل (VIN) من السطر المحدد (العمود الثاني فرسه index 1)
    String vinToDelete = fleetTable.getValueAt(selectedRow, 1).toString();
    
    // تأكيد الحذف من المستخدم لضمان الأمان
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete vehicle with VIN: " + vinToDelete + "?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 3. حذف المركبة من كائن مدير الأسطول برمجياً
        // (ملاحظة: تأكد أن كلاس FleetManager يحتوي على دالة حذف بالـ VIN، أو سنمر على القائمة ونحذفها)
        model.Vehicle target = null;
        for (model.Vehicle v : manager.getFleetList()) {
            if (v.getVin().equals(vinToDelete)) {
                target = v;
                break;
            }
        }
        
        if (target != null) {
            manager.getFleetList().remove(target); // مسحها من القائمة
            
            // 4. حفظ التعديل الجديد في الملف النصي فوراً
            database.DatabaseService.saveFleetData(manager);
            
            // 5. تحديث الجدول على الشاشة
            refreshTable();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Vehicle deleted successfully!");
        }
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        // 1. معرفة السطر المحدد
    int selectedRow = fleetTable.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a vehicle from the table to edit.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. جلب الـ VIN لمعرفة المركبة المستهدفة
    String vinToEdit = fleetTable.getValueAt(selectedRow, 1).toString();
    
    // 3. البحث عن المركبة في الأسطول
    for (model.Vehicle v : manager.getFleetList()) {
        if (v.getVin().equals(vinToEdit)) {
            try {
                // طلب البيانات الجديدة من المستخدم مع عرض القيمة القديمة لتسهيل التعديل
                String newModel = javax.swing.JOptionPane.showInputDialog(this, "Edit Vehicle Model:", v.getModel());
                if (newModel == null || newModel.trim().isEmpty()) return;
                
                String newOdoStr = javax.swing.JOptionPane.showInputDialog(this, "Edit Current Odometer (KM):", v.getCurrentOdometer());
                if (newOdoStr == null) return;
                double newOdometer = Double.parseDouble(newOdoStr);
                
                // 4. تحديث البيانات داخل الكائن باستخدام الـ Setters (مفهوم الـ Encapsulation)
                v.setModel(newModel);
                v.setCurrentOdometer(newOdometer);
                
                // 5. حفظ التعديلات في ملف قاعدة البيانات وتحديث الشاشة
                database.DatabaseService.saveFleetData(manager);
                refreshTable();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Vehicle updated successfully!");
                return;
                
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid input! Odometer must be a number.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addMaintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaintenanceButtonActionPerformed
        // TODO add your handling code here:
       try {
        // 1. فحص هل حدد المستخدم سيارة من الجدول بالفأرة أولاً
        int selectedRow = fleetTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a vehicle from the table first!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. إظهار الـ Combo Box ليختار المستخدم نوع الصيانة
        String[] maintenanceTypes = {"Oil Change", "Tire Replacement", "Gearbox Service"};
        String selectedService = (String) javax.swing.JOptionPane.showInputDialog(
                this, 
                "Select Maintenance Type:", 
                "New Maintenance Record", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, 
                null, 
                maintenanceTypes, 
                maintenanceTypes[0]
        );
        
        if (selectedService == null) return; // إذا أقفل المستخدم النافذة

        // 3. طلب التاريخ من المستخدم في نافذة سريعة
        String date = javax.swing.JOptionPane.showInputDialog(this, "Enter Date (YYYY-MM-DD):", "2026-06-22");
        if (date == null || date.trim().isEmpty()) return;

        // 4. جلب الـ VIN للمركبة المحددة لربط الصيانة بها
        String targetVin = fleetTable.getValueAt(selectedRow, 1).toString();
        
        // 5. البحث عن المركبة داخل الأسطول
        for (model.Vehicle v : manager.getFleetList()) {
            if (v.getVin().equals(targetVin)) {
                
                // التعديل السحري هنا: جلب السعر ديناميكياً حسب نوع المركبة (Polymorphism)
                double calculatedCost = v.getServiceCostByType(selectedService);
                
                // إنشاء كائن سجل الصيانة الجديد بالسعر المخصص للسيارة
                model.MaintenanceRecord newRecord = new model.MaintenanceRecord(selectedService, calculatedCost, date);
                
                // إضافة السجل الجديد لقائمة تاريخ صيانة هذه المركبة
                v.getMaintenanceHistory().add(newRecord); 
                
                // حفظ البيانات فوراً في ملف قاعدة البيانات النصي لكي لا تضيع
                database.DatabaseService.saveFleetData(manager);
                
                // إعلام المستخدم بنجاح العملية وعرض السعر الذكي التلقائي الذي تم حسابه
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Maintenance Record Added Successfully!\n" +
                        "Service: " + selectedService + "\n" +
                        "Cost for this Vehicle Type: $" + calculatedCost);
                break;
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_addMaintenanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addMaintenanceButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable fleetTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
